### ISSUE TITLE
How can I handle uuid and jsob in PGSQL

### ISSUE THREAD

**Issue by hajsf** [JuliaComputing/JuliaDB.jl#302] opened 2019-09-08 12:06 UTC
In my database, I've the below structure:
```sql
CREATE TABLE public.devices
(
    id uuid,
    data jsonb
)
```
When I run my query using this package, I got the below, how can I read the output properly?

![image](https://user-images.githubusercontent.com/46838626/64487958-20ba3d80-d24a-11e9-8d52-14e04a93d2b8.png)

**Comment by joshday** [comment] 2019-09-08 14:12
Not sure what you mean.  When the output is too wide, JuliaDB prints a summary instead of the actual table.  You can force the entire table to display with

```julia
IndexedTables.set_show_compact!(false)
```

**Comment by hajsf** [comment] 2019-09-09 17:02
@joshday  where shall I write this?

**Comment by joshday** [comment] 2019-09-09 17:17
In a Jupyter notebook cell.  The next time the table displays it will show the whole thing.

**Comment by hajsf** [comment] 2019-09-09 17:42
@joshday  not sure if I got your point, I got the below, even after restarting jupyter:
![image](https://user-images.githubusercontent.com/46838626/64552810-b33d0880-d340-11e9-99ce-0a8856f704d3.png)


I did not check `data[1]` and `data[2]` before, but this is what I get now, but as you see `JSON.parse` does not work on it :(:

![image](https://user-images.githubusercontent.com/46838626/64552895-eb444b80-d340-11e9-805b-49928b36e17f.png)
![image](https://user-images.githubusercontent.com/46838626/64553594-52aecb00-d342-11e9-80b8-45e375101bb4.png)

**Comment by joshday** [comment] 2019-09-09 18:47
Add `using IndexedTables` first.

I believe you'll need to `JSON.parse` each element one at a time.

**Comment by joshday** [comment] 2019-09-09 22:33
I'm going to close this since it's a usage question and not a bug report.  Try asking on slack/discourse if you need further help!

**Closed by joshday** 2019-09-09 22:33 UTC
